name: skripsi_rinaldo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.17.0-nullsafety.2
  provider: ^4.0.0
  fluttertoast: ^7.1.1
  shared_preferences: any
  flutter_form_builder: ^5.0.0
  flutter_pdfview: ^1.0.4
  path_provider: ^2.0.0-nullsafety.1
  image_picker: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Notosans
      fonts:
        - asset: assets/fonts/notosans_regular.ttf
        - asset: assets/fonts/notosans_bold.ttf
        - asset: assets/fonts/notosans_italic.ttf
          style: italic
        